networks:
  edgex-network:
    external: true
    name: edgexpert_edgex-network

services:
  pymodbus-sim:
    image: iotechsys/pymodbus-sim:1.0
    container_name: ${COMPOSE_PROJECT_NAME}
    command: --port 5020 --profile /pymodbus-sim-config.json --script /update_values.py
    ports:
      - ${SIM_PORT}:5020
    volumes:
      - type: bind
        source: ${PWD}/pymodbus-sim-config.json
        target: /pymodbus-sim-config.json
        read_only: true
      - type: bind
        source: ${PWD}/update_values.py
        target: /update_values.py
        read_only: true
    networks:
      - edgex-network